apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-5lo5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0065-tenant/tkrw-pr712-0075-0065-app/devfile-sample-5lo5@sha256:fa49ee1d5b817d881536aa035458bd39f31f2f4dd0ca68685b2c69b0096f0837
        name: my-nodejs
        resources: {}
status: {}
